
//! Autogenerated weights for `pallet_proof_of_location`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-11-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `arch`, CPU: `AMD Ryzen 5 7600 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_proof_of_location
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// pallets/proof-of-location/frame-weight-template.hbs
// --output
// pallets/proof-of-location/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_proof_of_location`.
pub trait WeightInfo {
	fn set_server_config() -> Weight;
	fn register_node() -> Weight;
	fn unregister_node() -> Weight;
	fn update_node_info() -> Weight;
	fn publish_rssi_data() -> Weight;
}

/// Weights for `pallet_proof_of_location` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ProofOfLocation::ServerConfig` (r:0 w:1)
	/// Proof: `ProofOfLocation::ServerConfig` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn set_server_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_407_000 picoseconds.
		Weight::from_parts(6_597_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ProofOfLocation::AddressRegistrationData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AddressRegistrationData` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::AccountData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3535`
		// Minimum execution time: 8_649_000 picoseconds.
		Weight::from_parts(8_920_000, 3535)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ProofOfLocation::AccountData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::ServerConfig` (r:0 w:1)
	/// Proof: `ProofOfLocation::ServerConfig` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::AddressRegistrationData` (r:0 w:1)
	/// Proof: `ProofOfLocation::AddressRegistrationData` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn unregister_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `135`
		//  Estimated: `3535`
		// Minimum execution time: 11_893_000 picoseconds.
		Weight::from_parts(12_174_000, 3535)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ProofOfLocation::AccountData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::AddressRegistrationData` (r:1 w:2)
	/// Proof: `ProofOfLocation::AddressRegistrationData` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn update_node_info() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `3535`
		// Minimum execution time: 13_925_000 picoseconds.
		Weight::from_parts(14_426_000, 3535)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ProofOfLocation::AccountData` (r:2 w:0)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::RssiData` (r:0 w:1)
	/// Proof: `ProofOfLocation::RssiData` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn publish_rssi_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `6080`
		// Minimum execution time: 14_426_000 picoseconds.
		Weight::from_parts(14_877_000, 6080)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ProofOfLocation::ServerConfig` (r:0 w:1)
	/// Proof: `ProofOfLocation::ServerConfig` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn set_server_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_407_000 picoseconds.
		Weight::from_parts(6_597_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ProofOfLocation::AddressRegistrationData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AddressRegistrationData` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::AccountData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3535`
		// Minimum execution time: 8_649_000 picoseconds.
		Weight::from_parts(8_920_000, 3535)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ProofOfLocation::AccountData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::ServerConfig` (r:0 w:1)
	/// Proof: `ProofOfLocation::ServerConfig` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::AddressRegistrationData` (r:0 w:1)
	/// Proof: `ProofOfLocation::AddressRegistrationData` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn unregister_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `135`
		//  Estimated: `3535`
		// Minimum execution time: 11_893_000 picoseconds.
		Weight::from_parts(12_174_000, 3535)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ProofOfLocation::AccountData` (r:1 w:1)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::AddressRegistrationData` (r:1 w:2)
	/// Proof: `ProofOfLocation::AddressRegistrationData` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn update_node_info() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `3535`
		// Minimum execution time: 13_925_000 picoseconds.
		Weight::from_parts(14_426_000, 3535)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ProofOfLocation::AccountData` (r:2 w:0)
	/// Proof: `ProofOfLocation::AccountData` (`max_values`: None, `max_size`: Some(70), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `ProofOfLocation::RssiData` (r:0 w:1)
	/// Proof: `ProofOfLocation::RssiData` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn publish_rssi_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `6080`
		// Minimum execution time: 14_426_000 picoseconds.
		Weight::from_parts(14_877_000, 6080)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
